### ISSUE TITLE
Nextcloud / Moodle Oauth2 Authentifizierung funktioniert nicht mehr nach Uprade von Nextcloud

### ISSUE THREAD

**Issue by dasistwas** [diehauswirtschaft/moodle-nextcloud#1]
Login via OAuth2 funktioniert nicht mehr. Fehlermeldung in Moodle:

```
error/Could not upgrade oauth token

Weitere Informationen über diesen Fehler
Debug-Info: 
Error code: Could not upgrade oauth token
$a contents:
Stack trace: 

    line 579 of /lib/oauthlib.php: moodle_exception thrown
    line 479 of /lib/oauthlib.php: call to oauth2_client->upgrade_token()
    line 905 of /lib/classes/oauth2/api.php: call to oauth2_client->is_logged_in()
    line 175 of /admin/tool/oauth2/issuers.php: call to core\oauth2\api::connect_system_account()
```

Problem in Nextcloud Log:

```
root@hauswirtschaft-nbg1-prod1:/var/log/apache2# grep "apps/oauth2/api/v1/token" cloud-access.log
116.203.176.60 - - [31/Oct/2021:00:30:02 +0200] "POST /index.php/apps/oauth2/api/v1/token HTTP/2.0" 401 1068 "-" "MoodleBot/3.9 (+https://intern.diehauswirtschaft.at)"
116.203.176.60 - - [31/Oct/2021:01:30:02 +0200] "POST /index.php/apps/oauth2/api/v1/token HTTP/2.0" 401 1062 "-" "MoodleBot/3.9 (+https://intern.diehauswirtschaft.at)"
116.203.176.60 - - [31/Oct/2021:02:30:01 +0100] "POST /index.php/apps/oauth2/api/v1/token HTTP/2.0" 401 1066 "-" "MoodleBot/3.9 (+https://intern.diehauswirtschaft.at)"
116.203.176.60 - - [31/Oct/2021:03:30:01 +0100] "POST /index.php/apps/oauth2/api/v1/token HTTP/2.0" 401 1060 "-" "MoodleBot/3.9 (+https://intern.diehauswirtschaft.at)"
116.203.176.60 - - [31/Oct/2021:04:30:01 +0100] "POST /index.php/apps/oauth2/api/v1/token HTTP/2.0" 401 1064 "-" "MoodleBot/3.9 (+https://intern.diehauswirtschaft.at)"
116.203.176.60 - - [31/Oct/2021:05:30:01 +0100] "POST /index.php/apps/oauth2/api/v1/token HTTP/2.0" 401 1066 "-" "MoodleBot/3.9 (+https://intern.diehauswirtschaft.at)"
116.203.176.60 - - [31/Oct/2021:06:02:36 +0100] "POST /index.php/apps/oauth2/api/v1/token HTTP/2.0" 401 1064 "-" "MoodleBot/3.9 (+https://intern.diehauswirtschaft.at)"

```
DB-Eintrag in Nextcloud brute force:
```

MariaDB [dhw_nextcloud]> SELECT * FROM oc_bruteforce_attempts;
+----+--------+------------+----------------+-------------------+-----------------------------------------------------------------------------+
| id | action | occurred   | ip             | subnet            | metadata                                                                    |
+----+--------+------------+----------------+-------------------+-----------------------------------------------------------------------------+
|  1 | login  | 1635681732 | 116.203.176.60 | 116.203.176.60/32 | {"user":"jLjjHUT96EnS0GMHeHpYsBsV7HmME3BI0UzK9WIswt88yMFVGmec6dVFEvJ2Gmat"} |
+----+--------+------------+----------------+-------------------+-----------------------------------------------------------------------------+
1 row in set (0.001 sec)
```

Schaut so aus als ob der Aufruf des Token APIs einen 401 Fehler auswirft.

**Comment by dasistwas** [comment]
# Lösungsversuche:

## Brute force Whitelist funktioniert nicht nach dieser Anleitung
https://help.nextcloud.com/t/how-to-remove-an-ip-from-the-whitelist-of-brute-force/90946/2

## Wer anderer hat das selbe Problem
https://help.nextcloud.com/t/nextcloud-22-oauth2-and-moodle/124319 Es gibt einen Issue dazu auf github: https://github.com/nextcloud/server/issues/28261

Im Issue wird auch wieder brute force blocking als Ursache vermutet, folgendes versucht
sudo -u www-data ./occ security:bruteforce:reset 116.203.176.60
Hat auch nix gebracht.
Anscheinend ist das der böse Commit:
https://github.com/nextcloud/server/commit/521bb30541277f6f5e6d939bf75328a9ce8322a9

**Comment by dasistwas** [comment]
OK, ich habe den Fix jetzt manuell in lib/base.php eingetragen. Zeilen 994ff

https://github.com/nextcloud/server/blob/03936d776272e5bd270fb185ad7bcb438cc635d7/lib/base.php#L994

Folgendes eingefügt:
```
				// Don't try to login when a client is trying to get a OAuth token.
				// OAuth needs to support basic auth too, so the login is not valid
				// inside Nextcloud and the Login exception would ruin it.
				if ($request->getRawPathInfo() !== '/apps/oauth2/api/v1/token') {
					self::handleLogin($request);
				}
```

Link zum Original-Fix:
https://github.com/nextcloud/server/pull/29320/commits/03936d776272e5bd270fb185ad7bcb438cc635d7

@stif falls das Probleme beim Upgrade macht, einfach die Änderung wieder Rückgängig machen kurz vor dem Upgrade. Aber denke, das müsste auch so funktionieren.

**Comment by sephentos** [comment]
Hey, ich habe das Issue https://github.com/nextcloud/server/issues/28261 
Ende Juli veröffentlicht. Scheinbar - so heißt es - soll es mit v22.2.1 fixed sein - bei mir funktioniert OAuth aber weiterhin nicht. 

Läuft es bei euch inzwischen?

Absolut unbegreiflich für mich, wie man seitens Nextcloud einen solchen Fehler fast 5 Monate liegen lässt...

**Comment by dasistwas** [comment]
@sephentos Ich denke der Commit wird erst in v23 aufgenommen. Diese wurde aber gerade veröffentlicht: https://github.com/nextcloud/server/tags

**Comment by botic** [comment]
> Absolut unbegreiflich für mich, wie man seitens Nextcloud einen solchen Fehler fast 5 Monate liegen lässt...

Nextcloud hat leider einige Bugs lange liegen gelassen, wo ich mir schon auf den Kopf gegriffen hab. Ich hab mal vermutet: Die sind voll mit dem Einbau von neuen Features beschäftigt, statt auf die Qualität einzelner Komponenten zu schauen. Die spüren einfach die harte Konkurrenz und müssen massiv Kunden gewinnen, damit sie gegen Owncloud und andere bestehen können.
